INSERT INTO Country
VALUES(NOW(), FALSE, 'A', 'South Africa', 'A', 'H', 1),
 (NOW(), FALSE, 'A', 'Ivory Coast', 'J', 'N', 1),
 (NOW(), FALSE, 'A', 'Not Assigned', 'P', '0', 1),
 (NOW(), FALSE, 'B', 'Angola', 'A', 'E', 1),
 (NOW(), FALSE, 'B', 'Kenya', 'F', 'K', 1),
 (NOW(), FALSE, 'B', 'Tanzania', 'L', 'R', 1),
 (NOW(), FALSE, 'B', 'Not Assigned', 'S', '0', 1),
 (NOW(), FALSE, 'C', 'Benin', 'A', 'E', 1),
 (NOW(), FALSE, 'C', 'Madagascar', 'F', 'K', 1),
 (NOW(), FALSE, 'C', 'Tunisia', 'L', 'R', 1),
 (NOW(), FALSE, 'C', 'Not Assigned', 'S', '0', 1),
 (NOW(), FALSE, 'D', 'Egypt', 'A', 'E', 1),
 (NOW(), FALSE, 'D', 'Morocco', 'F', 'K', 1),
 (NOW(), FALSE, 'D', 'Zambia', 'L', 'R', 1),
 (NOW(), FALSE, 'D', 'Not Assigned', 'S', '0', 1),
 (NOW(), FALSE, 'E', 'Ghana', 'A', 'E', 1),
 (NOW(), FALSE, 'E', 'Mozambique', 'F', 'K', 1),
 (NOW(), FALSE, 'E', 'Not Assigned', 'L', '0', 1),
 (NOW(), FALSE, 'F', 'India', 'A', 'E', 1),
 (NOW(), FALSE, 'F', 'Nigeria', 'F', 'K', 1),
 (NOW(), FALSE, 'F', 'Not Assigned', 'L', '0', 1),
 (NOW(), FALSE, 'G', 'Not Assigned', 'A', '0', 1),
 (NOW(), FALSE, 'H', 'Not Assigned', 'A', '0', 1),
 (NOW(), FALSE, 'J', 'Japan', 'A', '0', 2),
 (NOW(), FALSE, 'K', 'Sri Lanka', 'A', 'E', 2),
 (NOW(), FALSE, 'K', 'Isreal', 'F', 'K', 2),
 (NOW(), FALSE, 'K', 'South Korea', 'L', 'R', 2),
 (NOW(), FALSE, 'K', 'Kazakhstan', 'S', '0', 2),
 (NOW(), FALSE, 'L', 'China', 'A', '0', 2),
 (NOW(), FALSE, 'M', 'India', 'A', 'E', 2),
 (NOW(), FALSE, 'M', 'Indonesia', 'F', 'K', 2),
 (NOW(), FALSE, 'M', 'Thailand', 'L', 'R', 2),
 (NOW(), FALSE, 'M', 'Myanmar', 'S', 'S', 2),
 (NOW(), FALSE, 'M', 'Not Assigned', 'T', '0', 2),
 (NOW(), FALSE, 'N', 'Iran', 'A', 'E', 2),
 (NOW(), FALSE, 'N', 'Pakistan', 'F', 'K', 2),
 (NOW(), FALSE, 'N', 'Turkey', 'L', 'R', 2),
 (NOW(), FALSE, 'N', 'Not Assigned', 'S', '0', 2),
 (NOW(), FALSE, 'P', 'Philippines', 'A', 'E', 2),
 (NOW(), FALSE, 'P', 'Singapore', 'F', 'K', 2),
 (NOW(), FALSE, 'P', 'Malaysia', 'L', 'R', 2),
 (NOW(), FALSE, 'P', 'Not Assigned', 'S', '0', 2),
 (NOW(), FALSE, 'R', 'UAE', 'A', 'E', 2),
 (NOW(), FALSE, 'R', 'Taiwan', 'F', 'K', 2),
 (NOW(), FALSE, 'R', 'Vietnam', 'L', 'R', 2),
 (NOW(), FALSE, 'R', 'Saudi Arabia', 'S', '0', 2),
 (NOW(), FALSE, 'S', 'United Kingdom', 'A', 'M', 3),
 (NOW(), FALSE, 'S', 'Eastern Germany', 'N', 'T', 3),
 (NOW(), FALSE, 'S', 'Poland', 'U', 'Z', 3),
 (NOW(), FALSE, 'S', 'Latvia', '1', '4', 3),
 (NOW(), FALSE, 'S', 'Not Assigned', '5', '0', 3),
 (NOW(), FALSE, 'T', 'Switzerland', 'A', 'H', 3),
 (NOW(), FALSE, 'T', 'Czech Republic', 'J', 'P', 3),
 (NOW(), FALSE, 'T', 'Hungary', 'R', 'V', 3),
 (NOW(), FALSE, 'T', 'Portugal', 'W', '1', 3),
 (NOW(), FALSE, 'T', 'Not Assigned', '2', '0', 3),
 (NOW(), FALSE, 'U', 'Not Assigned', 'A', 'G', 3),
 (NOW(), FALSE, 'U', 'Denmark', 'H', 'M', 3),
 (NOW(), FALSE, 'U', 'Ireland', 'N', 'T', 3),
 (NOW(), FALSE, 'U', 'Romania', 'U', 'Z', 3),
 (NOW(), FALSE, 'U', 'Not Assigned', '1', '4', 3),
 (NOW(), FALSE, 'U', 'Slovakia', '5', '7', 3),
 (NOW(), FALSE, 'U', 'Not Assigned', '8', '0', 3),
 (NOW(), FALSE, 'V', 'Austria', 'A', 'E', 3),
 (NOW(), FALSE, 'V', 'France', 'F', 'R', 3),
 (NOW(), FALSE, 'V', 'Spain', 'S', 'W', 3),
 (NOW(), FALSE, 'V', 'Serbia', 'X', '2', 3),
 (NOW(), FALSE, 'V', 'Croatia', '3', '5', 3),
 (NOW(), FALSE, 'V', 'Estonia', '6', '0', 3),
 (NOW(), FALSE, 'W', 'Germany', 'A', '0', 3),
 (NOW(), FALSE, 'X', 'Bulgaria', 'A', 'E', 3),
 (NOW(), FALSE, 'X', 'Greece', 'F', 'K', 3),
 (NOW(), FALSE, 'X', 'Netherlands', 'L', 'R', 3),
 (NOW(), FALSE, 'X', 'USSR', 'S', 'W', 3),
 (NOW(), FALSE, 'X', 'Luxembourg', 'X', '2', 3),
 (NOW(), FALSE, 'X', 'Russia', '3', '0', 3),
 (NOW(), FALSE, 'Y', 'Belgium', 'A', 'E', 3),
 (NOW(), FALSE, 'Y', 'Finland', 'F', 'K', 3),
 (NOW(), FALSE, 'Y', 'Malta', 'L', 'R', 3),
 (NOW(), FALSE, 'Y', 'Sweden', 'S', 'W', 3),
 (NOW(), FALSE, 'Y', 'Norway', 'X', '2', 3),
 (NOW(), FALSE, 'Y', 'Belarus', '3', '5', 3),
 (NOW(), FALSE, 'Y', 'Ukraine', '6', '0', 3),
 (NOW(), FALSE, 'Z', 'Italy', 'A', 'R', 3),
 (NOW(), FALSE, 'Z', 'Not Assigned', 'S', 'W', 3),
 (NOW(), FALSE, 'Z', 'Slovenia', 'X', '2', 3),
 (NOW(), FALSE, 'Z', 'Lithuania', '3', '5', 3),
 (NOW(), FALSE, 'Z', 'Not Assigned', '6', '0', 3),
 (NOW(), FALSE, '1', 'United States', 'A', '0', 4),
 (NOW(), FALSE, '2', 'Canada', 'A', '0', 4),
 (NOW(), FALSE, '3', 'Mexico', 'A', '0', 4),
 (NOW(), FALSE, '4', 'United States', 'A', '0', 4),
 (NOW(), FALSE, '5', 'United States', 'A', '0', 4),
 (NOW(), FALSE, '6', 'Australia', 'A', 'W', 5),
 (NOW(), FALSE, '6', 'Not Assigned', 'X', '0', 5),
 (NOW(), FALSE, '7', 'New Zealand', 'A', 'E', 5),
 (NOW(), FALSE, '7', 'Not Assigned', 'F', '0', 5),
 (NOW(), FALSE, '8', 'Argentina', 'A', 'E', 6),
 (NOW(), FALSE, '8', 'Chile', 'F', 'K', 6),
 (NOW(), FALSE, '8', 'Ecuador', 'L', 'R', 6),
 (NOW(), FALSE, '8', 'Peru', 'S', 'W', 6),
 (NOW(), FALSE, '8', 'Venezuela', 'X', '2', 6),
 (NOW(), FALSE, '8', 'Not Assigned', '3', '0', 6),
 (NOW(), FALSE, '9', 'Brazil', 'A', 'E', 6),
 (NOW(), FALSE, '9', 'Colombia', 'F', 'K', 6),
 (NOW(), FALSE, '9', 'Paraguay', 'L', 'R', 6),
 (NOW(), FALSE, '9', 'Uruguay', 'S', 'W', 6),
 (NOW(), FALSE, '9', 'Trinidad & Tobago', 'X', '2', 6),
 (NOW(), FALSE, '9', 'Brazil', '3', '9', 6),
 (NOW(), FALSE, '9', 'Not Assigned', '0', '0', 6),
 (NOW(), FALSE, '0', 'Not Assigned', 'A', '0', 6)