INSERT INTO Manufacturer
VALUES(NOW(), FALSE, 'Honda Motor Company, Ltd.', 'Honda', 'Japanese auto manufacturer.', 1963, 0, null),
    (NOW(), FALSE, 'Toyota Motor Corporation', 'Toyota', 'Japanese multinational automotive manufacturer headquartered in Toyota, Aichi, Japan.', 1937, 0, null),
    (NOW(), FALSE, 'Volkswagen', 'Volkswagen', 'German automaker founded on 28 May 1937 by the German Labour Front under Adolf Hitler and headquartered in Wolfsburg.', 1937, 0, null),
    (NOW(), FALSE, 'Ford Motor Company', 'Ford', 'American multinational automaker headquartered in Dearborn, Michigan, a suburb of Detroit.', 1903, 0, null),
    (NOW(), FALSE, 'Mercedes-Benz', 'Mercedes-Benz', 'Global automobile marque and a division of the German company Daimler AG.', 1926, 0, null),
    (NOW(), FALSE, 'Groupe Renault', 'Renault', 'French multinational automobile manufacturer established in 1899.', 1899, 0, null),
    (NOW(), FALSE, 'Bavarian Motor Works', 'BMW', 'German multinational company which currently produces automobiles and motorcycles, and also produced aircraft engines until 1945.', 1916, 0, null),
    (NOW(), FALSE, 'BMW M GmbH', 'BMW', 'Sub-brand for BMW performance vehicles.', 1972, 0, 7),
    (NOW(), FALSE, 'BMW i', 'BMW', 'Sub-brand for BMW electric vehicles.', 2011, 0, 7),
    (NOW(), FALSE, 'MINI', 'Mini', 'British automotive marque, owned by BMW', 1959, 0, 7),
    (NOW(), FALSE, 'Rolls-Royce Motor Cars Ltd.', 'Rolls-Royce', 'Rolls-Royce Motor Cars Limited is a wholly owned subsidiary of BMW', 1973, 0, 7),
    (NOW(), FALSE, 'BMW Motorrad', 'BMW', 'Motorcycle brand owned by BMW', 1923, 0, null),
    (NOW(), FALSE, 'Hyundai Motor Company', 'Hyundai', 'South Korean multinational automotive manufacturer headquartered in Seoul, South Korea.', 1967, 0, null),
    (NOW(), FALSE, 'Kia Motor Corporation', 'KIA', 'Second-largest automobile manufacturer in South Korea, following the Hyundai Motor Company.', 1944, 0, null),
    (NOW(), FALSE, 'Nissan Motor Company Ltd.', 'Nissan', 'Japanese multinational automobile manufacturer headquartered in Nishi-ku, Yokohama.', 1933, 0, null),
    (NOW(), FALSE, 'Infiniti', 'Infinity', ' Luxury vehicle division of Japanese automaker Nissan.', 1989, 0, 15),
    (NOW(), FALSE, 'Datsun', 'Datsun', 'Low-cost vehicles for emerging markets.', 1931, 0, 15),
    (NOW(), FALSE, 'Isuzu Motors Ltd.', 'Isuzu', 'Japanese commercial vehicles and diesel engine manufacturing company headquartered in Tokyo.', 1937, 0, null),
    (NOW(), FALSE, 'Mahindra and Mahindra Ltd. (M&M)', 'Mahindra', 'It is one of the largest vehicle manufacturers by production in India and the largest manufacturer of tractors in the world.', 1945, 0, null),
    (NOW(), FALSE, 'Great Wall Motors Company Ltd.', 'GWM', 'Chinese automobile manufacturer headquartered in Baoding, Hebei, China.', 1984, 0, null),
    (NOW(), FALSE, 'AB Volvo', 'Volvo', 'Swedish multinational manufacturing company headquartered in Gothenburg.', 1927, 0, null)