INSERT INTO WMI
VALUES()


/*
--- HONDA 
'JHM', 'HONDA MOTOR CO., LTD', 'Passenger Car'
'1HG', 'HONDA OF AMERICA MFG., INC.', 'Passenger Car'
'5KB', 'HONDA MFG., ALABAMA., LLC.', 'Passenger Car'
'2HG', 'HONDA OF CANADA MFG., INC.', 'Passenger Car'
'SHH', 'HONDA OF THE U.K. MFG., LTD.', 'Passenger Car'
'3HG', 'HONDA DE MEXICO', 'Passenger Car'
'19X', 'HONDA MFG., INDIANA., LLC.', 'Passenger Car'
'JH4', 'HONDA MOTOR CO., LTD', 'Passenger Car'
'JHL', 'HONDA MOTOR CO., LTD', 'MPV'
'JH1', 'HONDA MOTOR CO., LTD', 'Truck '
'19U', 'HONDA OF AMERICA MFG., INC.', 'Passenger Car'
'5J6', 'HONDA OF AMERICA MFG., INC.', 'MPV'
'5J8', 'HONDA OF AMERICA MFG., INC.', 'MPV'
'5J7', 'HONDA OF AMERICA MFG., INC.', 'Truck '
'5J0', 'HONDA OF AMERICA MFG., INC.', 'Truck '
'5KC', 'HONDA MFG., ALABAMA., LLC.', 'Passenger Car'
'5FN', 'HONDA MFG., ALABAMA., LLC.', 'MPV'
'5FR', 'HONDA MFG., ALABAMA., LLC.', 'MPV'
'5FP', 'HONDA MFG., ALABAMA., LLC.', 'Truck '
'5FS', 'HONDA MFG., ALABAMA., LLC.', 'Truck '
'2HH', 'HONDA OF CANADA MFG., INC.', 'Passenger Car'
'2HK', 'HONDA OF CANADA MFG., INC.', 'MPV'
'2HN', 'HONDA OF CANADA MFG., INC.', 'MPV'
'2HJ', 'HONDA OF CANADA MFG., INC.', 'Truck '
'2HU', 'HONDA OF CANADA MFG., INC.', 'Truck '
'SHS', 'HONDA OF THE U.K. MFG., LTD.', 'MPV'
'3CZ', 'HONDA DE MEXICO', 'MPV'
'JH2', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'1HF', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'YC1', 'HONDA OF AMERICA MFG., INC.', 'Motorcycle'
'3H1', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'19V', 'HONDA MFG., INDIANA., LLC.', 'Passenger Car'
'ZDC', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'MLH', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'LAL', 'SUNDIRO HONDA MOTORCYCLE CO., LTD.', 'Motorcycle'
'RLH', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'VTM', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'LWB', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'LRY', 'CHONGQING GUANGYU MOTORCYCLE MANUFACTURE CO., LTD.', 'Motorcycle'
'LSR', 'CHONGQING HI-BIRD MOTORCYCLE INDUSTRY CO., LTD.', 'Motorcycle'
'LYE', 'CHONGQING KAIER MOTORCYCLE MANUFACTURING CO.,', 'Motorcycle'
'LLC', 'CHONGQING KINLON MOTORCYCLE MANUFACTURE CO., LTD', 'Motorcycle'
'LWG', 'CHONGQING HUANSONG INDUSTRIES (GROUP) CO., LTD.', 'Motorcycle'
'LRP', 'CHONGQING RATO POWER CO., LTD.', 'Motorcycle'
'LB4', 'CHONGQING YINXIANG MOTORCYCLE (GROUP) CO., LTD.', 'Motorcycle'
'JR2', 'AMERICAN HONDA MOTOR CO., INC.', 'MPV'
'LC3', 'WUXI JINHONG MOTORCYCLE CO., LTD', 'Motorcycle'
'1J9390', 'JOYHON, INC.', 'Trailer'
'L0H', 'CHANGZHOU ZHONGMAO MACHINERY CO., LTD', 'Trailer'
'LHJ', 'CHONGQING ASTRONAUTICAL BASHAN MOTORCYCLE MANUFACTURER.CO., LTD,', 'Motorcycle'
'1M9822', 'MARATHON METALWORKS', 'Trailer'
'LUA', ' CHONGQING HENSIM GROUP CO., LTD.', 'Motorcycle'
'L4Y', 'QINGQI GROUP NINGBO RHON MOTORCYCLE CO., LTD', 'Motorcycle'
'L82', 'JIANGMEN SINO-HONGKONG BAOTIAN MOTORCYCLE INDUSTRIAL CO., LTD.', 'Motorcycle'
'L69FYK', 'SHANDONG ZHONGTONG FEIYAN AUTOMOBILE CO. LTD.', 'Motorcycle'
'L5Y', 'TAIZHOU ZHONGNENG MOTORCYCLE CO., LTD.', 'Motorcycle'
'LSB', 'SHANGHAI HUIZHONG AUTOMOTIVE MANUFACTURING CO., LTD', 'Trailer'
'LLA', 'SHANGHAI HONLING MOTORCYCLE MANUFACTURE CO., LTD.', 'Motorcycle'
'LKX', 'CHONGQING KINGTON INDUSTRY GROUP CO., LTD.', 'Motorcycle'
'LZX', 'CHONGQING SHUANGQING MECHANICAL & ELECTRICAL CO.', 'Motorcycle'
'L1P', 'CHONGQUING DAIJING MOTORCYCLES CO', 'Motorcycle'
'1M9019', 'MARATHON HOMES CORPORATION', 'Trailer'
'R12', 'Xinri E-Vehicle Hongkong Co., Limited', 'Motorcycle'
'LXY', 'CHONGQING SHINERAY MOTORCYCLE CO., LTD.', 'Motorcycle'
'9C2', 'AMERICAN HONDA MOTOR CO., INC.', 'Motorcycle'
'JH3', 'HONDA MOTOR CO., LTD', 'Motorcycle'
'478', 'HONDA MFG., INDIANA., LLC.', 'Motorcycle'
'VTD', 'MONTESA HONDA SA', 'Motorcycle'
'LY4', 'CHONGQING YINGANG SCIENCE & TECHNOLOGY (GROUP) CO., LTD.', 'Motorcycle'
'R1V', 'RONGCHENG COMPAKS (HONG KONG) NEW ENERGY AUTOMOBILE CO LTD', 'Trailer'
'2M9004', 'MARATHON EQUIPMENT LTD ', 'Trailer'
'7FA', 'HONDA MFG., INDIANA., LLC.', 'MPV'
'1G9340', 'GRYPHON BIKES & CHOPPERS', 'Motorcycle'
'LMF', 'JIANGMEN ZHONGYU MOTOR (GROUP) CO., LTD.', 'Motorcycle'
'R1A', 'JHC NEW ENERGY VEHICLE HONGKONG CO.,LTD', 'Low Speed Vehicle (LSV)'
'LPP', 'NANCHANG AIRCRAFT MFG. CO ( HONGDU MACHINERY PLANT)', 'Motorcycle'
'SA9112', 'HONNOR MARINE LTD', 'Trailer'
'R2L', 'HONGDU ELECTRIC VEHICLE HONGKONG CO.,LIMITED', 'Motorcycle'
'LE6', 'HONGDOU GROUP CHITUMA MOTORCYCLE COMPANY', 'Motorcycle'

-- HONDA SAE
'19U', 'American Honda Motor Co Inc', 'Passenger Car'
'19V', 'Honda Manufacturing of Indiana LLC', 'Passenger Car'
'19X', 'Honda Manufacturing of Indiana LLC', 'Passenger Car'
'1G9', 'Gryphon Bikes & Choppers', 'Motorcycles - Complete, Street-Use'
'1H9', 'Honey RV', 'Park Model Recreational Trailer'
'1HF', 'American Honda Motor Co Inc', ''
'1HG', 'Honda of America Mfg Inc', 'Automobiles'
'1J9', 'Joyhon Inc', 'Trailers'
'1M9', 'Marathon Homes Corporation', 'Travel Trailers & Fifth Wheels'
'1M9', 'Marathon Equipment Co', 'Recycling Trailers'
'1M9', 'Marathon Industries Inc', 'Trailers'
'1M9', 'Marathon Metalworks LLC', 'Trailers'
'1M9', 'Marathon Intl Inc.', 'Trailers'
'1P9', 'Phelps Honey Wagon Inc.', 'Sewage Tanks For Campers'
'2A9', 'Les Ateliers St - Honore Inc', ''
'2HF', 'Honda Canada Inc', 'Motorcycles'
'2HG', 'Honda Canada Inc', 'Cars'
'2HH', 'Honda Canada Inc', 'Passenger Car'
'2HJ', 'Honda Canada Inc', 'Light Duty Trucks'
'2HK', 'Honda Canada Inc', 'Multipurpose Passenger Vehicle'
'2HN', 'Honda Canada Inc', 'Multi-Purpose Vehicles'
'2HU', 'Honda Canada Inc', 'Trucks'
'2M9', 'Marathon Equipment Ltd', 'Trailers'
'2M9', 'Marathon Road Maintenance Equipment', 'Trailers'
'2M9', 'Marathon Marine Manufacturing (1996) Ltd', 'Trailers'
'2M9', 'Marathon Equipment Inc.', 'Trailers'
'3CZ', 'Honda de Mexico SA de CV', 'Automovil, modelo CR-V'
'3H1', 'Honda de Mexico SA de CV', 'Motorcycles'
'3HG', 'Honda de Mexico SA de CV', 'Passenger Cars'
'478', 'Honda of America Mfg Inc', 'Off-Road Vehicle'
'4P6', 'Phontom Trailers', 'Utility Trailers'
'5FN', 'Honda Manufacturing of Alabama LLC', 'Multi-Purpose Passenger Vehicles'
'5FP', 'Honda Manufacturing of Alabama LLC', 'Light Duty Trucks'
'5FR', 'Honda Manufacturing of Alabama LLC', 'Multi-Purpose Passenger Vehicles'
'5FS', 'Honda Manufacturing of Alabama LLC', 'Light Duty Trucks'
'5J0', 'Honda of America Mfg Inc', 'Light-Duty Truck (Ltd)'
'5J6', 'Honda of America Mfg Inc', 'Multi-Purpose Vehicle (Mpv)'
'5J7', 'Honda of America Mfg Inc', 'Light-Duty Truck (Ltd)'
'5J8', 'Honda of America Mfg Inc', 'Multi-Purpose Vehicle (Mpv)'
'5KB', 'Honda Manufacturing of Alabama LLC', 'Passenger Vehicle'
'5KC', 'Honda Manufacturing of Alabama LLC', 'Passenger Vehicle'
'6H6', 'Honda Australia Motorcycles', 'Motorcycles'
'6MB', 'Prochon Pty Ltd', 'Motorcycles'
'7A3', 'Honda New Zealand Limited', ''
'7B4', 'Blue Wing Honda Limited', ''
'7B6', 'Honda New Zealand Limited', ''
'7FA', 'Honda Manufacturing of Indiana LLC', 'Multi-Purpose Passenger Vehicle'
'8C3', 'Honda Motor de Argentina S.A.', 'passenger car'
'8CH', 'Honda Motor de Argentina S A', 'Motorcycle'
'93H', 'Honda Automoveis do Brasil Ltda', 'Automobile'
'9C2', 'Moto Honda Da Amazonia Ltda.', 'Motorcycles'
'9F9', 'Talleres Y Transportes Pachon Ltda.', 'Trailers'
'BF0', 'Honda Motorcycle Kenya Limited', 'Motorcycles, street-use'
'BL0', 'Honda Nigeria Ltd.', 'Motorcycles'
'BL1', 'Honda Automobile Western Africa Ltd.', 'Passenger Car'
'JH1', 'Honda Motor Co Ltd', 'Truck (Complete Vehicle)'
'JH2', 'Honda Motor Co Ltd', 'Motorcycle'
'JH3', 'Honda Motor Co Ltd', 'All-Terrain Vehicle'
'JH4', 'Honda Motor Co Ltd', 'Reserved'
'JH5', 'Honda Motor Co Ltd', 'Reserved'
'JHL', 'Honda Motor Co Ltd', 'Reserved'
'JHM', 'Honda Motor Co Ltd', 'Passenger Car'
'JHW', 'Honda Motor Co Ltd', 'Reserved'
'JHX', 'Honda Motor Co Ltd', 'Reserved'
'JHY', 'Honda Motor Co Ltd', 'Reserved'
'JHZ', 'Honda Motor Co Ltd', 'Reserved'
'JR1', 'Honda Motor Co Ltd', 'Reserved'
'JR2', 'Honda Motor Co Ltd', 'Reserved'
'JR3', 'Honda Motor Co Ltd', 'Reserved'
'JR4', 'Honda Motor Co Ltd', 'Reserved'
'JR5', 'Honda Motor Co Ltd', 'Reserved'
'JR6', 'Honda Motor Co Ltd', 'Reserved'
'JR7', 'Honda Motor Co Ltd', 'Reserved'
'JR8', 'Honda Motor Co Ltd', 'Reserved'
'L06', 'Chongqing Jianjia Motive Power Machinery', 'ATV'
'L0D', 'Chongqing Panlong Technology Dev Co Ltd', 'ATV'
'L0H', 'Changzhou Zhongmao Machinery Co. Ltd.', 'Trailers'
'L0W', 'Chongqing Haosen Motorcycle Co Ltd.', 'ATVs, dirt bikes'
'L1K', 'Chongqing Hengtong Coach Co. Ltd.', 'Bus'
'L1P', 'Chongqing Dajiang Motorcycle Co. Ltd.', 'Motorcycle'
'L1R', 'Chongqing Beyond Special Vehicle Co Ltd.', 'ATVs'
'L20', 'The Agriculture Car of Hongyun Factory', 'Low-speed Goods Vehicle'
'L28', 'Chongqing Junesun Special Vehicle Co Ltd', 'ATV'
'L3A', 'Chongqing Jialing Special Equip. Co. Ltd', 'Bus, Truck, Trailer, Incomplete Vehicle'
'L4Y', 'Qingqi Group Ningbo Rhon Motorycle Co Lt', 'Motorcycle, ATV'
'L5Y', 'Taizhou Zhongneng Motorcycle Co Ltd', 'Motorcycle'
'L63', 'Zhongtong Automobile Industry Group Co.', 'Low-speed Goods Vehicle'
'L69', 'Shandong Zhongtong Feiyan Automobile Co', 'Bus, Truck, Trailer'
'L6U', 'Zhejiang Chaozhong Industrial Co Ltd', 'ATV, Scooter'
'L6X', 'Chongqing Dongben Industry Co Ltd', 'Motorcycles'
'L7J', 'Jiangsu Zhongxing Motorcycle Co Ltd', 'Motorcycles'
'L80', 'Chongqing Lianfei Motorcycle Co Ltd', 'ATV'
'L82', 'Jiangmen Sino-Hong Kong Baotian Motorcyc', 'Motorcycle'
'L9E', 'Chongqing SAJAO Mechanical & Electrical', 'ATVs'
'LA4', 'Shanghai Zhongmo Industrial Co', 'Motorcycles'
'LA9', 'Zhengzhou Hongda Automobile Industry Co', 'Trailers'
'LA9', 'Zhengzhou Hongda Automobile Industry Co', 'Trailer'
'LA9', 'Zhongshan Haiyue Automobile Industry Co', 'Special Vehicle'
'LA9', 'Bengbu Zhenchong Anli Engrg Machine Co L', 'Special Vehicle'
'LA9', 'Nanchong Machinery Plant Of Sichuan', 'Special Vehicle'
'LA9', 'Beijing Zhonghuan Kinetics Heavy Vehicle', 'Truck, Trailer'
'LA9', 'Beijing Zhongqi Yunsong Automobile', 'Truck, Bus'
'LA9', 'Baoding Hongye Petroleum Prospecting', 'Truck'
'LA9', 'Beijing Beizhong Automobile Refitting Co', 'Truck'
'LA9', 'Beijing Zhonghuan Kinetics Heavy Vehicle', 'Truck, Trailer'
'LA9', 'Chongqing Chuanjiang Vehicle Mfg Co Ltd', 'Bus, Truck'
'LA9', 'Chongqing Jinguan Automobile Mfg Co Ltd', 'Bus, Truck'
'LA9', 'Chongqing Changjiang Western Heavy Truck', 'Trucks'
'LA9', 'Chongqing Ruichi Automotive Industry Co.', 'Bus, Truck'
'LA9', 'Chongqing Kairui Spec Purp Vehicle Plant', 'Truck, Trailer'
'LA9', 'Dong'E Zhongya Special Vehicle Co. Ltd.', 'Truck, trailer'
'LA9', 'Dong'E Zhongya Special Vehicle Co. Ltd.', 'Trucks, Trailers'
'LA9', 'Shandong Donghong Industry Trade Co. Ltd', 'Trucks'
'LA9', 'Dailian Zhongqi Kamaz Special Automobile', 'Truck, Trailer'
'LA9', 'Liaoning Lingyuan Hongling Automotive Gr', 'Truck, Incomplete Vehicle'
'LA9', 'Tianjin HongFengtai Automobile Repacking', 'Truck, Trailer'
'LA9', 'Tangshan Hongda Vehicles Refitment Co Lt', 'Trucks, Trailers'
'LA9', 'Hebei Hongchang Tianma Special Pur Veh C', 'Trucks, Trailers'
'LA9', 'Zhangzhou Hongyu Special Vehicle Co Ltd', 'Trailer, Truck'
'LA9', 'Hebei Hongtai Special Truck Co Ltd', 'Truck, Trailer'
'LA9', 'Tangshan Honda Vehicles Refitment Co', 'Truck, Trailer, Special Vehicle'
'LA9', 'Hongyun Automotive Corporation', 'Truck, Trailer'
'LA9', 'Jiangsu Zhonghuan Machinery Co Ltd', 'Low-speed Goods Vehicle'
'LA9', 'Jiangsu Zhongyi Auto Co Ltd', 'Trucks'
'LA9', 'Zhejiang Zhongyu Automobile Co. Ltd.', 'Bus'
'LA9', 'Zhongtong Automobile Industry Group Co.', 'Truck, Trailer, Bus'
'LA9', 'Chongqing Dima Industry Co Ltd', 'Bus, Truck'
'LA9', 'Chongqing South DIMA Special Purpose Veh', 'Truck'
'LA9', 'Sichuan Qinhong Construction Machinery F', 'Special Vehicle'
'LA9', 'Hubei Century Zhongyuan Vehicle Co Ltd', 'Truck'
'LA9', 'Liangshan Hongda Vehicle Makes Co Ltd', 'Truck, Trailer'
'LA9', 'Zhongcheng Group Shandong Longkou Motor', 'Truck, Bus, Trailer'
'LA9', 'Beijing Municipal Zhongyan Construction', 'Truck, Trailer'
'LA9', 'Shijiazhuang Zhongbo Auto Co. Ltd.', 'Bus'
'LA9', 'Shiyan Zhonglong Automobile Co Ltd.', 'Truck'
'LA9', 'Tieling Hongda Vehicle Modification Co L', 'Trailer, Truck'
'LA9', 'Zhongxing Special Automobile Mfg of Tang', 'Truck, Trailer'
'LA9', 'Wuhan Zhongzheng Chem Equip Co Ltd', 'Trailer, Truck'
'LA9', 'Wuzhong Wanxin Industrial Co Ltd', 'Trailers'
'LA9', 'Xinjiang Hongda Heavy-Duty Machinery', 'Truck'
'LA9', 'Xin Hong Chang Special Vehicle Co Ltd', 'Truck, trailer'
'LA9', 'Xinjiang Zhongtong Bus Company Ltd.', 'Bus'
'LA9', 'Xiangfan Xin Zhongchang Special Motor', 'Trailer'
'LA9', 'Yancheng Zhongwei Bus Co Ltd', 'Bus'
'LA9', 'Dagang Oilfield Group Zhongcheng Machine', 'Truck'
'LA9', 'Beijing Zhongjifuqing Special Purpose', 'Truck, Trailer'
'LA9', 'Suzhou Zhong-ou Auto Co Ltd', 'Bus'
'LA9', 'Jiangsu Yanghong Special Vehicle Mfg Co.', 'Truck, Trailer'
'LA9', 'Shandong Hongyunda Special Purpose', 'Truck, Trailer'
'LAD', 'Jiangsu Zhongqi Dongzheng Yinxiang Motor', 'Motorcycles'
'LAH', 'Chongqing Shuangqing Mechanical &', 'Motorcycles'
'LAL', 'Sundiro Honda Motorcycle Co Ltd', 'Motorcycles, Mopeds'
'LAP', 'Chongqing Jianshe Motorcycle Co Ltd.', 'Motorcycle, ATV'
'LAV', 'Hongying Motorcycle Factory', 'Motor-Scooters'
'LAZ', 'Chongqing Guangyi Motorcycle Co Ltd', 'Motorcycles'
'LB4', 'Chongqing Yinxiang Motorcycle Group Co', 'Motorcycles'
'LB9', 'Guangdong Zengcheng Zhongjingyangcheng', 'Truck'
'LBP', 'China Chongqing Jainshe', 'Motorcycle'
'LC3', 'Wuxi Jinhong Motorcycle Co. Ltd.', 'Motorcycle'
'LC4', 'Chongqing Liyang Jiatong Motorcycle Mfg', 'Motorcycle'
'LCG', 'Chongqing Shuangqing Mechanical &', 'Motorcycle'
'LCN', 'Chongqing Lifan Automobile Co Ltd', 'Pass Car,Bus,Truck,Trailer,Incom Ve'
'LCZ', 'Chongqing Heavy Vehicle Group Co Ltd', 'Trailer, Truck'
'LDJ', 'Chongqing Dajiang Industry (Group)', 'Special Vehicle'
'LDS', 'Chongqing Endurance Shanhua Special Vehi', 'Truck, Bus'
'LDY', 'Zhongtong Bus Holding Co Ltd', 'Bus, Incomplete Vehicle'
'LHA', 'Hebei Hongxing Automobile Manufacturing', 'Truck, Bus, Passenger Car, Incomplete Vehicle'
'LHC', 'Gaobeidian Zhongke Huabei Auto Co Ltd', 'Passenger Car,Bus, Truck'
'LHG', 'Guangzhou Honda Automobile Co LTD', 'Car'
'LHJ', 'Chongqing Astronautic Bashan', 'Motorcycle'
'LJ7', 'Zhongxing Group Co. Ltd.', 'Motorcycle'
'LKX', 'Chongqing Kington Liyang Motorcycle Manu', 'Motorcycle'
'LL7', 'Shanxi Hanzhong Bus Co Ltd', 'Bus, Truck'
'LLA', 'Shanghai Honling Motorcycle Manufacture', 'Motorcycle'
'LLC', 'Chongqing Loncin Motor Co Ltd', 'Motorcyle, Moped, ATV'
'LLM', 'Zhejiang Hongzhou Motorcycle Co Ltd', 'Motorcycle'
'LLS', 'Chonche Group Xi'an Lishan', 'Bus & Special Bus'
'LLV', 'Chongqing Lifan Passenger Vehicle Co Ltd', 'Passenger Cars'
'LMF', 'Jiangmen Zhongyu Motor (Group) Co Ltd', ''
'LPH', 'Guangzhou Hongqiao Bus Manufacture Co Lt', 'Bus'
'LPP', 'Jiangxi Hongdu Aviation Industry Group C', 'Mopeds, Motorcycles'
'LRA', 'Ji'Nan Hongqi Kaiwote Auto Maker Co', 'Trailer'
'LRP', 'Chongqing Rato Power Co. Ltd.', 'ATVs, Motorcycles'
'LRY', 'Chongqing Guangyu Motorcycle Manufacture', 'Motorcycle'
'LS4', 'Chongqing Changan Automobile Co Ltd', 'Bus, Incomplete Vehicle'
'LS5', 'Chongqing Changan Automobile Co Ltd', 'Passenger Car'
'LS6', 'Chongqing Changan Automobile Co Ltd', 'Passenger Car'
'LS9', 'Shandong Hongda Construction Machine', 'Truck'
'LSC', 'Chongqing Changan Automobile Co Ltd', 'Truck, Incomplete Vehicle, Trailer, Low-speed Goods Vehicle'
'LSL', 'Chongqing Changan Automobile Co Ltd', 'Truck, Incomplete Vehicle, Trailer, Low-speed Goods Vehicle'
'LSN', 'Shandong Zhongqi Motorcycle (Group) Manu', 'Motorcycle'
'LSP', 'Jinan Zhonglu Special Automobile Co Ltd', 'Truck, Trailer'
'LSR', 'Chongqing Hi-Bird Motorcycle Industry Co', 'Motorcycle'
'LT7', 'Hebei Hongda Special Purpose Vehicle Mfg', 'Truck, Trailer'
'LTA', 'Hebei Zhongxing Automobile Co Ltd', 'Truck, Bus (Special Bus)'
'LTE', 'Chongqing Charming Motorcycle Mfg Co Ltd', 'ATV'
'LTM', 'Sundiro Honda Motorcycle Co Ltd', 'Motorcycle, Moped'
'LTX', 'Tianjin Zhongyang Xunda Motor Co Ltd', 'Motorcycles'
'LTZ', 'Foshan Nanhai Zhongmo Science & Tech', 'Motorcycles'
'LUA', 'Chongqing Hensim Group Co Ltd', 'Motorcycles'
'LUC', 'Honda Automobile (China) Co Ltd.', 'Passenger Car'
'LUH', 'Wuxi Hongyan Motorcycle Limited Company', 'Motorcycle'
'LVH', 'Dongfeng Honda Automobile Co Ltd', 'Passenger Car, Bus'
'LW8', 'Chongqing Wanhu Mechanical & Electrical', 'Motorcycle, ATV'
'LWB', 'Wuyang-Honda Motors (Guangzhou) Co Ltd', 'Motorcycle, Moped'
'LWG', 'Chongqing Huansong  Industries Group Co', 'Motorcycle, ATV'
'LWM', 'Chongqing Wonjan Motorcycle Mfg Co Ltd', 'Motorcycle'
'LX8', 'Chongqing Xgjao Motorcycle Co Ltd', 'Motorcycle, Moped'
'LXC', 'Chongqing Tiema Industries Corporation', 'Truck, Trailer, Incomplete Vehicle'
'LXY', 'Chongqing Shineray Motorcycle Co Ltd', 'Motorcycle'
'LY0', 'Jiangsu Hongzhou Jinfu Vehicle Co. Ltd.', 'Motorcycle, ATV'
'LY3', 'Zhongyou Special Vehicle Corp Ltd.', 'Trailer, Truck'
'LY4', 'Chongqing Yingang Science & Tech Group', 'Motorcycle, Moped'
'LYE', 'Chongqing Kaler Motorcycle Mfg Co Ltd', 'Motorcycles'
'LYJ', 'Beijing ZhongdaYanjing Auto Co Ltd', 'Bus, Incomplete Vehicle'
'LYR', 'Chongqing Shuangqing Mechanical &', 'Motorcycle'
'LZ6', 'Foshan Zhongfo Special Automobile Works', 'Bus, Truck'
'LZF', 'Chongqing Hongyan Motor Co Ltd', 'Truck,Bus,Trailer,Incomplete Vehicl'
'LZP', 'Zhongshan Guochi Motorcycle Industrial C', 'Motorcycles'
'LZX', 'Chongqing Shuangqing Mech & Elect Co Ltd', 'Motorcycle'
'MAK', 'Honda Siel Cars India Ltd', 'Car'
'ME4', 'Honda Motorcycle & Scooter India Pvt Ltd', 'Two Wheelers'
'MLH', 'Thai Honda Manufacturing Co Ltd', ''
'MRH', 'Honda Automobile (Thailand) Co Ltd', 'Passenger Cars'
'MS8', 'Tan Chong Motor (Myanmar) Co Ltd', 'Passenger Car'
'NFB', 'Honda Atlas Cars Pakistan Ltd', 'Passenger Cars'
'NLA', 'Honda Turkiye AS', ''
'NMH', 'Honda Anadolu Motosiklet', ''
'NS5', 'The Hong Da Group LLC', 'Motorcycles, three wheeled cargo'
'NS6', 'The Hong Xiang Group LLC', 'Motorcycles, scooters, mopeds'
'PAD', 'Honda Cars Philippines Inc', 'Passenger Cars'
'PMH', 'Honda Malaysia Sdn Bhd', 'Passenger Cars & Multi Purpose Veh.'
'PMK', 'Boon Siew Honda Sdn Bhd', 'PMK'
'PMY', 'Hong Leong Yamaha Motor Sdn.Bhd', 'Motorcycles & Mopeds'
'PN6', 'Tan Chong Industrial Equipment Sdn. Bhd.', 'Light Duty Truck, Heavy Duty Truck, Bus'
'PN8', 'Tan Chong And Sons Motor Company Sdn Bhd', ''
'PND', 'Tan Chong And Sons Motor Company Sdn Bhd', 'Trucks And Buses'
'PS0', 'Bangladesh Honda Private Limited', 'Motorcycles'
'R12', 'XINRI E-vehicle Hong Kong Co. Ltd.', 'E-scooter, quadricycle, motorcycle'
'R13', 'HK Hongchang Industrial Limited', 'e-motor, motorcycles'
'R17', 'HongKong Brother Traffic Tech. Grp Co Lt', 'Motorcycles'
'R18', 'HongKong Yuanming Vehicle Co. Ltd.', 'Motorcycles'
'R1A', 'JHC New Energy Vehicle HongKong Co Ltd', 'Motorcycles, quadricycle, E-Scooter'
'R1B', 'JHC New Energy Vehicle HongKong Co Ltd', 'Passenger Car'
'R1C', 'TAIQI Hong Kong Electric Vehicle Co Ltd', 'Electric Vehicles'
'R1D', 'HongKong Lider Vehicle Co. Ltd.', 'Electric Vehicles'
'R1J', 'China Jiayuan Power (Hongkong) Limited', 'Motorcycles, quadricycle, E-scooter'
'R1K', 'Aierma (Hong Kong) Technology Comp. Ltd.', 'Elec. Motorcycles, Elec. Bikes'
'R1L', 'China Jiayuan Power (Hongkong) Limited', 'Trucks'
'R1M', 'Chongqing Senda Technologies Co. Limited', 'Motorcycles'
'R1P', 'Yangzhou Vulcan (Hongkong) Machinery', 'Trailers'
'R1R', 'Dongma Vehicle Hongkong Co Limited', 'Motorcycles, e-scooter, quadricycle'
'R1U', 'Somoto (HongKong) Motorcycle Co Ltd', 'e-bike, motorcycles'
'R1V', 'Rongcheng Compaks (Hong Kong) New Energy', 'Trailers'
'R26', 'Taihong Technology Limited', 'Motorcycles'
'R27', 'Hong Kong CHJ Automotive Technology Ltd', 'Motorcycles, two, three and four wheel'
'R28', 'HongKong Forethought Industry Co Ltd.', 'Motorcycles'
'R2B', 'HongKong Ruipeng Power Technology Ltd', 'Motorcycles, two, three, four wheel'
'R2C', 'HongKong Top Outdoor Sports Technology', 'Motorcycles, two, three and four wheel'
'R2L', 'Hongdu Electric Vehicle Hongkong Co.', 'Motorcycles, e-scooter, quadricycle'
'R2R', 'Huangzhonghuang Vehicle Industry Co. Ltd', 'Motorcycles'
'R2Y', 'HL Corp (Hong Kong) Limited', 'Motorcycles'
'R30', 'HongKong Qinglan New Energy Vehicle', 'Motorcycles, two, three and four wheel'
'RKT', 'Honda Taiwan Co Ltd', 'Multi-Purpose Veh & Passenger Cars'
'RLH', 'Honda Vietnam Company Ltd', 'Motorcycles'
'SHH', 'Honda UK Ltd', 'Motor Vehicles'
'SHJ', 'Honda of the UK Mfg Ltd', ''
'SHR', 'Honda UK Ltd', 'Motor Vehicles'
'SHS', 'Honda of the UK Mfg Ltd', ''
'TX9', 'Jorge Honorio Da Silva & Filho LDA', 'Trailer, Recreational, Commercial'
'VF9', 'Ampa Rhone', 'Remorques'
'VF9', 'Jacky Pichon', 'Cycles'
'VF9', 'Stey-Motos Honda', 'Motos'
'VF9', 'Ste Gaston Reverchon Industries', 'Vehicules'
'VF9', 'Etablisements Claude Mathon', 'Remorques'
'VF9', 'Reverchon Sud', 'Vehicules 113 Routiers'
'VF9', 'Megaphone France', 'Vehicules Routiers Agricole'
'VTD', 'Montesa Honda SA', ''
'VTM', 'Montesa Honda SA', ''
'W09', 'Leo Honold Kg Frahrzeugbau', 'Anhanger'
'X89', 'Sergo Ordzhonikidze', ''
'X9D', 'Scientific Prod Assoc Athon-Impulse', ''
'XL9', 'Anthon Schalkers Aanhangwagens Oegstgees', ''
'YA9', 'Ets F Honnorez', 'Commercial Trailers'
'YC1', 'Honda Belgium NV', ''
'YG9', 'Honkalammen KyKiteen Teekoo-Tuote', 'Light Trailers'
'YG9', 'Honkalampi Saatio', 'O1'
'YGE', 'Honkalampi-Saatio', 'Trailers O1, O2'
'ZDC', 'Honda Italia Industriales SpA', ''
*/